In [1]:
import keras

Using TensorFlow backend.


In [2]:
from keras import Sequential
from keras.layers import Flatten,Dense

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [4]:
dataset = pd.read_csv('Customer_Churn_Modelling.csv')

In [5]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
x= dataset.drop(labels=['CustomerId','Surname','RowNumber','Exited'],axis =1)

In [7]:
y =dataset['Exited']
x.head(10)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   
5          645     Spain    Male   44       8  113755.78              2   
6          822    France    Male   50       7       0.00              2   
7          376   Germany  Female   29       4  115046.74              4   
8          501    France    Male   44       4  142051.07              2   
9          684    France    Male   27       2  134603.88              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10  
5          1               0        149756.71  
6          1               1         10062.80  
7          1               0        119346.88  
8          0               1         74940.50  
9          1               1         71725.73

In [8]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
label1=LabelEncoder()
x['Geography'] = label1.fit_transform(x['Geography'])
x['Gender'] = label1.fit_transform(x['Geography'])

x.head(10)

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       2   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       2   43       2  125510.82              1   
5          645          2       2   44       8  113755.78              2   
6          822          0       0   50       7       0.00              2   
7          376          1       1   29       4  115046.74              4   
8          501          0       0   44       4  142051.07              2   
9          684          0       0   27       2  134603.88              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10  
5          1               0        149756.71  
6          1               1         10062.80  
7          1               0        119346.88  
8          0               1         74940.50  
9          1               1         71725.73

In [11]:
x.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       2   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       2   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [12]:
x= pd.get_dummies(x,drop_first=True ,columns = ['Geography'])

x.head(10)

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       2   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       2   43       2  125510.82              1          1   
5          645       2   44       8  113755.78              2          1   
6          822       0   50       7       0.00              2          1   
7          376       1   29       4  115046.74              4          1   
8          501       0   44       4  142051.07              2          0   
9          684       0   27       2  134603.88              1          1   

   IsActiveMember  EstimatedSalary  Geography_1  Geography_2  
0               1        101348.88            0            0  
1               1        112542.58            0            1  
2               0        113931.57            0            0  
3               0         93826.63            0            0  
4               1         79084.10            0            1  
5               0        149756.71            0            1  
6               1         10062.80            0            0  
7               0        119346.88            1            0  
8               1         74940.50            0            0  
9               1         71725.73            0            0

In [14]:
from sklearn.preprocessing import StandardScaler

In [18]:
x_train, x_test, y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0,stratify =y)

In [19]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until


In [20]:
x_train

array([[-1.24021723, -0.90267262,  0.77986083, ...,  1.64099027,
        -0.57812007, -0.57504086],
       [ 0.75974873,  0.30491617, -0.27382717, ..., -1.55587522,
         1.72974448, -0.57504086],
       [-1.72725557, -0.90267262, -0.9443559 , ...,  1.1038111 ,
        -0.57812007, -0.57504086],
       ...,
       [-0.51484098,  0.30491617,  0.87565065, ..., -1.01507508,
         1.72974448, -0.57504086],
       [ 0.73902369, -0.90267262, -0.36961699, ..., -1.47887193,
        -0.57812007, -0.57504086],
       [ 0.95663657,  1.51250495, -1.32751517, ...,  0.50945854,
        -0.57812007,  1.73900686]])

# Build ANN

In [22]:
model = Sequential()
model.add(Dense(x.shape[1],activation= 'relu',input_dim= x.shape[1]))
model.add(Dense(128,activation = 'relu'))
model.add(Dense(1,activation='sigmoid'))

In [23]:
 model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [24]:
model.fit(x_train,y_train.to_numpy(),batch_size=10,epochs=10,verbose=1)

Epoch 1/10
8000/8000 [==============================] - 5s 622us/step - loss: 0.4644 - accuracy: 0.8005
Epoch 2/10
8000/8000 [==============================] - 3s 415us/step - loss: 0.3833 - accuracy: 0.8441
Epoch 3/10
8000/8000 [==============================] - 3s 341us/step - loss: 0.3580 - accuracy: 0.8562
Epoch 4/10
8000/8000 [==============================] - 2s 298us/step - loss: 0.3482 - accuracy: 0.8615
Epoch 5/10
8000/8000 [==============================] - 2s 273us/step - loss: 0.3449 - accuracy: 0.8624
Epoch 6/10
8000/8000 [==============================] - 2s 263us/step - loss: 0.3419 - accuracy: 0.8612
Epoch 7/10
8000/8000 [==============================] - 2s 271us/step - loss: 0.3404 - accuracy: 0.8616
Epoch 8/10
8000/8000 [==============================] - 2s 276us/step - loss: 0.3382 - accuracy: 0.8635
Epoch 9/10
8000/8000 [==============================] - 2s 276us/step - loss: 0.3380 - accuracy: 0.8619
Epoch 10/10
8000/8000 [==============================] - 2s 250u

In [25]:
y_pred = model.predict_classes(x_test)

In [26]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]])

In [27]:
y_test

1344    1
8167    0
4747    0
5004    1
3124    1
1940    1
2090    0
3298    0
8364    1
9485    0
3088    0
617     1
7211    0
9253    0
9743    0
1546    0
3475    0
6623    0
7594    0
2347    1
9583    0
6473    0
8104    0
6486    0
9747    1
6187    0
2458    0
5875    0
9317    1
7170    0
       ..
9086    0
2249    0
1971    0
8379    1
6450    0
7223    1
6143    0
7582    0
4679    0
7060    0
9709    0
1045    0
7141    0
5148    0
4868    0
3407    0
5400    0
9241    0
9454    0
1046    1
7791    0
959     0
6488    0
1487    1
9574    0
9107    0
8249    0
8337    0
6279    1
412     0
Name: Exited, Length: 2000, dtype: int64

In [28]:
model.evaluate(x_test,y_test.to_numpy())

2000/2000 [==============================] - 0s 102us/step


[0.3608559573888779, 0.8500000238418579]

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [30]:
confusion_matrix(y_test,y_pred)

array([[1558,   35],
       [ 265,  142]], dtype=int64)

In [31]:
accuracy_score(y_test,y_pred)

0.85